Repository atlassian/voyager, pull requests merged in 2019-02, with the labels that each got.

#106 Auto-bump dependencies
  Gopkg.lock
  vendor/github.com/atlassian/smith/cmd/smith/app/bundle_controller.go
  vendor/github.com/atlassian/smith/it/BUILD.bazel
  vendor/github.com/atlassian/smith/it/utils_for_tests.go
  vendor/github.com/atlassian/smith/pkg/controller/bundlec/BUILD.bazel
  vendor/github.com/atlassian/smith/pkg/controller/bundlec/controller.go
  vendor/github.com/atlassian/smith/pkg/specchecker/builtin/process_deployment.go
Labels: bump-dep

#109 Resolve TODOs
  pkg/apis/composition/v1/types.go
  pkg/apis/formation/v1/types.go
  pkg/apis/orchestration/v1/types.go
Labels: cleanup

#108 Auto-bump dependencies
  Gopkg.lock
  vendor/github.com/atlassian/smith/pkg/specchecker/builtin/process_deployment.go
  vendor/github.com/atlassian/smith/pkg/specchecker/hash.go
Labels: bump-dep

#112 Remove unused ASAP server code
  pkg/util/pkiutil/BUILD.bazel
  pkg/util/pkiutil/asap_server.go
Labels: cleanup

#121 Auto-bump dependencies
  Gopkg.lock
  vendor/github.com/atlassian/smith/it/BUILD.bazel
  vendor/github.com/atlassian/smith/it/utils_for_tests.go
Labels: bump-dep

#110 Cleanup status construction code
  pkg/composition/controller.go
  pkg/composition/controller_test.go
  pkg/formation/controller.go
Labels: cleanup

#117 Cleanup some bits in Synchronization
  pkg/synchronization/controller.go
  pkg/synchronization/controller_test.go
Labels: cleanup

#123 Strict YAML parsing
  cmd/aggregator/app/options.go
  cmd/computionadmission/app/options.go
  cmd/formation/app/options.go
  cmd/monitor/app/options.go
  cmd/ops/app/options.go
  cmd/orchestration/app/options.go
  cmd/orchestrationadmission/app/options.go
  cmd/replicationadmission/app/options.go
  cmd/reporter/app/options.go
  cmd/reporterreporter/app/options.go
  cmd/secretive/app/config.go
  cmd/svccatadmission/app/options.go
  cmd/synchronization/app/options.go
  pkg/composition/crd/crd_test.go
  pkg/composition/options.go
  pkg/composition/plumbing_for_test.go
  pkg/composition/testdata/basic.ld.location1.yaml
  pkg/composition/testdata/basic.ld.location2.yaml
  pkg/composition/testdata/basic.sd.output.yaml
  pkg/composition/testdata/interop_error.ld.location1.yaml
  pkg/composition/testdata/interop_error.ld.location2.yaml
  pkg/composition/testdata/interop_error.sd.output.yaml
  pkg/composition/testdata/missing_ld_status.ld.location2.yaml
  pkg/composition/testdata/missing_ld_status.sd.output.yaml
  pkg/composition/testdata/transition.ld.location1.yaml
  pkg/composition/testdata/transition.ld.location2.yaml
  pkg/composition/testdata/updated_status.ld.location1.yaml
  pkg/composition/testdata/updated_status.ld.location2.yaml
  pkg/composition/testdata/updated_status.sd.input.yaml
  pkg/composition/testdata/updated_status.sd.output.yaml
  pkg/creator/server/options/config_file_options.go
  pkg/execution/computionadmission/admission.go
  pkg/execution/plugins/atlassian/iamrole/iam_role_manager_test.go
  pkg/formation/controller.go
  pkg/formation/testdata/simple.ld.input.yaml
  pkg/formation/testdata/simple.ld.output.yaml
  pkg/formation/testdata/simple.state.output.yaml
  pkg/formation/testdata/test_resource_no_update.ld.yaml
  pkg/formation/testdata/test_resource_no_update.state.yaml
  pkg/formation/testdata/test_resource_update.ld.yaml
  pkg/formation/testdata/test_resource_update.state.yaml
  pkg/orchestration/controller.go
  pkg/orchestration/crd/crd_test.go
  pkg/orchestration/testdata/simple_status.bundle.output.yaml
  pkg/orchestration/testdata/simple_status.state.input.yaml
  pkg/orchestration/testdata/simple_status.state.output.yaml
  pkg/orchestration/testdata/status_aggregation.bundle.output.yaml
  pkg/orchestration/testdata/status_aggregation.state.input.yaml
  pkg/orchestration/testdata/status_aggregation.state.output.yaml
  pkg/orchestration/testdata/test_resource_no_update.bundle.yaml
  pkg/orchestration/testdata/test_resource_no_update.state.yaml
  pkg/orchestration/testdata/test_resource_update.bundle.yaml
  pkg/orchestration/testdata/test_resource_update.state.yaml
  pkg/synchronization/controller_test.go
  pkg/util/testutil/testdata.go
Labels: cleanup, enhancement

#129 Auto-bump dependencies
  Gopkg.lock
  vendor/github.com/atlassian/ctrl/logz/logz.go
  vendor/github.com/atlassian/ctrl/process/generic.go
  vendor/github.com/atlassian/ctrl/process/generic_worker.go
Labels: bump-dep

#137 Use types
  pkg/orchestration/wiring/wiringutil/oap/types.go
  pkg/orchestration/wiring/wiringutil/oap/wiring.go
Labels: cleanup

#140 Auto-bump dependencies
  Gopkg.lock
  vendor/github.com/atlassian/smith/it/BUILD.bazel
  vendor/github.com/atlassian/smith/it/utils_for_tests.go
  vendor/github.com/atlassian/smith/pkg/controller/bundlec/controller.go
Labels: bump-dep

#147 Auto-bump dependencies
  Gopkg.lock
  vendor/github.com/atlassian/smith/pkg/apis/smith/v1/types.go
Labels: bump-dep

#148 Cleanup aggregation test
  pkg/aggregator/api_handler_test.go
Labels: cleanup

#156 Auto-bump dependencies
  Gopkg.lock
  pkg/opsgenie/it/client_manual_test.go
  pkg/trebuchet/server/apiserver/apiserver.go
  vendor/github.com/atlassian/ctrl/process/generic_worker.go
Labels: bump-dep

#171 Auto-bump dependencies
  Gopkg.lock
  vendor/github.com/atlassian/smith/pkg/controller/bundlec/BUILD.bazel
  vendor/github.com/atlassian/smith/pkg/controller/bundlec/controller_crd_event_handler.go
  vendor/github.com/atlassian/smith/pkg/controller/bundlec/resource_sync_task.go
  vendor/github.com/atlassian/smith/pkg/store/bundle.go
Labels: bump-dep

#172 Auto-bump dependencies
  Gopkg.lock
Labels: bump-dep

#173 Auto-bump dependencies
  Gopkg.lock
  pkg/execution/plugins/common.go
  pkg/execution/plugins/testing/utils_for_tests.go
  pkg/orchestration/wiring/wiringutil/service_binding.go
  vendor/github.com/atlassian/smith/pkg/controller/bundlec/resource_sync_task.go
  vendor/github.com/atlassian/smith/pkg/specchecker/builtin/process_service_binding.go
  vendor/github.com/atlassian/smith/pkg/store/catalog.go
  vendor/github.com/kubernetes-incubator/service-catalog/cmd/controller-manager/app/BUILD.bazel
  vendor/github.com/kubernetes-incubator/service-catalog/cmd/controller-manager/app/controller_manager.go
  vendor/github.com/kubernetes-incubator/service-catalog/cmd/healthcheck/framework/healthcheck.go
  vendor/github.com/kubernetes-incubator/service-catalog/cmd/svcat/output/binding.go
  vendor/github.com/kubernetes-incubator/service-catalog/cmd/svcat/plugin/BUILD.bazel
  vendor/github.com/kubernetes-incubator/service-catalog/cmd/svcat/plugin/install.go
  vendor/github.com/kubernetes-incubator/service-catalog/cmd/svcat/plugin/manifest.go
  vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/testing/fuzzer.go
  vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/types.go
  vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1beta1/plan.go
  vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1beta1/types.go
  vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
  vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/validation/binding.go
  vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/validation/instance.go
  vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-incubator/service-catalog/pkg/controller/BUILD.bazel
  vendor/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go
  vendor/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_binding.go
  vendor/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_clusterservicebroker.go
  vendor/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_instance.go
  vendor/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_servicebroker.go
  vendor/github.com/kubernetes-incubator/service-catalog/pkg/openapi/openapi_generated.go
  vendor/github.com/kubernetes-incubator/service-catalog/pkg/registry/servicecatalog/binding/storage.go
  vendor/github.com/kubernetes-incubator/service-catalog/pkg/svcat/service-catalog/binding.go
  vendor/github.com/kubernetes-incubator/service-catalog/pkg/svcat/service-catalog/instance.go
  vendor/github.com/kubernetes-incubator/service-catalog/plugin/pkg/admission/broker/authsarcheck/admission.go
  vendor/github.com/kubernetes-incubator/service-catalog/plugin/pkg/admission/servicebindings/lifecycle/admission.go
  vendor/github.com/kubernetes-incubator/service-catalog/test/e2e/walkthrough.go
  vendor/gopkg.in/go-playground/validator.v9/baked_in.go
  vendor/gopkg.in/go-playground/validator.v9/doc.go
  vendor/gopkg.in/go-playground/validator.v9/regexes.go
  vendor/gopkg.in/go-playground/validator.v9/struct_level.go
  vendor/k8s.io/apimachinery/pkg/runtime/codec.go
  vendor/k8s.io/apiserver/pkg/server/storage/storage_codec.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
Labels: bump-dep

#175 Cleanup reference construction and usage
  pkg/orchestration/wiring/ec2compute/v2/plugin.go
  pkg/orchestration/wiring/k8scompute/plugin.go
  pkg/orchestration/wiring/platformdns/plugin.go
  pkg/orchestration/wiring/sqs/plugin.go
  pkg/orchestration/wiring/testdata/asapkey.basicdep.bundle.yaml
  pkg/orchestration/wiring/testdata/e2e.tests.bundle.yaml
  pkg/orchestration/wiring/testdata/ec2compute-rename.bundle.yaml
  pkg/orchestration/wiring/testdata/ec2compute.asapkey.bundle.yaml
  pkg/orchestration/wiring/testdata/ec2compute.basicdep.bundle.yaml
  pkg/orchestration/wiring/testdata/ec2compute.customrdsreplica.bundle.yaml
  pkg/orchestration/wiring/testdata/ec2compute.rds.bundle.yaml
  pkg/orchestration/wiring/testdata/ec2compute.withcustomups.bundle.yaml
  pkg/orchestration/wiring/testdata/ec2compute.withups.bundle.yaml
  pkg/orchestration/wiring/testdata/k8scompute.basicdep.bundle.yaml
  pkg/orchestration/wiring/testdata/k8scompute.nodefaults.bundle.yaml
  pkg/orchestration/wiring/testdata/k8scompute.nohpa.bundle.yaml
  pkg/orchestration/wiring/testdata/k8scompute.probes.nodefaults.bundle.yaml
  pkg/orchestration/wiring/testdata/k8scompute.rename.bundle.yaml
  pkg/orchestration/wiring/testdata/k8scompute.sameminmax.bundle.yaml
  pkg/orchestration/wiring/testdata/platformdns.bundle.yaml
  pkg/orchestration/wiring/testdata/platformdns.multipleresources.bundle.yaml
  pkg/orchestration/wiring/testdata/sns.sqs.bundle.yaml
  pkg/orchestration/wiring/wiringutil/BUILD.bazel
  pkg/orchestration/wiring/wiringutil/iam/iam.go
  pkg/orchestration/wiring/wiringutil/iam/iam_test.go
  pkg/orchestration/wiring/wiringutil/knownshapes/bindable_iam_accessible.go
  pkg/orchestration/wiring/wiringutil/knownshapes/ingress_endpoint.go
  pkg/orchestration/wiring/wiringutil/knownshapes/sns_subscribable.go
  pkg/orchestration/wiring/wiringutil/libshapes/BUILD.bazel
  pkg/orchestration/wiring/wiringutil/libshapes/libshapes.go
  pkg/orchestration/wiring/wiringutil/service_binding.go
  pkg/orchestration/wiring/wiringutil/util.go
Labels: cleanup

#177 NONE: Remove unused function
  types.go
Labels: cleanup

#178 Deterministic map expansion order
  pkg/util/templating/templating.go
Labels: bug
