Repository atlassian/voyager, pull requests merged in 2019-01, with the labels that each got.

#18 Entangler does not depend on Orchestration
  cmd/reporter/app/controller_constructor.go
  pkg/composition/BUILD.bazel
  pkg/composition/controller.go
  pkg/execution/computionadmission/BUILD.bazel
  pkg/execution/computionadmission/admission.go
  pkg/orchestration/BUILD.bazel
  pkg/orchestration/controller.go
  pkg/orchestration/types.go
  pkg/orchestration/wiring/BUILD.bazel
  pkg/orchestration/wiring/entangler.go
  pkg/orchestration/wiring/entangler_test.go
  pkg/orchestration/wiring/testdata/k8scompute.withingressandlabel.state.yaml
  pkg/reporter/BUILD.bazel
  pkg/reporter/api_handler.go
  pkg/reporter/api_handler_test.go
  pkg/reporter/controller.go
  pkg/synchronization/BUILD.bazel
  pkg/synchronization/controller.go
  pkg/util/layers/BUILD.bazel
  pkg/util/layers/layers.go
Labels: cleanup

#21 Pass the resource contract to the dependant resource
  pkg/orchestration/wiring/entangler.go
Labels: bug

#20 Autowiring v2, step 2 - known shapes
  Makefile
  pkg/orchestration/wiring/wiringplugin/BUILD.bazel
  pkg/orchestration/wiring/wiringplugin/shapes.go
  pkg/orchestration/wiring/wiringplugin/types.go
  pkg/orchestration/wiring/wiringplugin/unstructured_shape.go
  pkg/orchestration/wiring/wiringplugin/zz_generated.deepcopy.go
  pkg/orchestration/wiring/wiringutil/knownshapes/BUILD.bazel
  pkg/orchestration/wiring/wiringutil/knownshapes/bindable_environment_variables.go
  pkg/orchestration/wiring/wiringutil/knownshapes/bindable_iam_accessible.go
  pkg/orchestration/wiring/wiringutil/knownshapes/types_test.go
  pkg/orchestration/wiring/wiringutil/knownshapes/zz_generated.deepcopy.go
Labels: enhancement

#23 Move json schema helper to avoid the world depending on apiext server
  BUILD.bazel
  pkg/api/README
  pkg/api/schema/BUILD.bazel
  pkg/api/schema/json_schema.go
  pkg/composition/BUILD.bazel
  pkg/composition/client.go
  pkg/creator/BUILD.bazel
  pkg/creator/handler.go
  pkg/formation/BUILD.bazel
  pkg/formation/client.go
  pkg/orchestration/BUILD.bazel
  pkg/orchestration/client.go
  types.go
Labels: cleanup

#32 Use typed schema conversion rather than going to/from JSON
  pkg/api/schema/schematest/BUILD.bazel
  pkg/api/schema/schematest/schematest.go
  pkg/composition/crd/BUILD.bazel
  pkg/composition/crd/crd_test.go
  pkg/orchestration/crd/BUILD.bazel
  pkg/orchestration/crd/crd_test.go
Labels: cleanup

#34 Silence linter warning
  pkg/execution/svccatadmission/rps/testing/testutil.go
Labels: cleanup

#35 Build race binaries instead of pure ones by default
  cmd/cmd.bzl
  cmd/crd/BUILD.bazel
  cmd/showenv/BUILD.bazel
Labels: cleanup

#39 Print test names in ci mode
  .bazelrc
  Makefile
Labels: bug, enhancement

#45 ConfigMap with service metadata should be parsed by controller
  pkg/orchestration/BUILD.bazel
  pkg/orchestration/controller.go
  pkg/orchestration/wiring/BUILD.bazel
  pkg/orchestration/wiring/entangler.go
  pkg/orchestration/wiring/entangler_test.go
Labels: cleanup

#46 Fix ingress resource to respect naming convention
  pkg/orchestration/wiring/kubeingress/plugin.go
  pkg/orchestration/wiring/kubeingress/plugin_test.go
  pkg/orchestration/wiring/testdata/e2e.tests.bundle.yaml
  pkg/orchestration/wiring/testdata/internaldns.bundle.yaml
  pkg/orchestration/wiring/testdata/internaldns.multiplealias.bundle.yaml
  pkg/orchestration/wiring/testdata/internaldns.multipleresources.bundle.yaml
  pkg/orchestration/wiring/testdata/k8scompute.withingress.bundle.yaml
  pkg/orchestration/wiring/testdata/k8scompute.withingressanddefaulttimeout.bundle.yaml
  pkg/orchestration/wiring/testdata/k8scompute.withingressandlabel.bundle.yaml
  pkg/orchestration/wiring/testdata/k8scompute.withingressandtimeout.bundle.yaml
Labels: bug

#44 Remove unused contract parts
  pkg/orchestration/wiring/wiringplugin/types.go
Labels: cleanup

#49 Removed deprecated code no longer needed after migrating to resource contracts
  pkg/orchestration/wiring/ec2compute/common/common.go
  pkg/orchestration/wiring/entangler.go
  pkg/orchestration/wiring/k8scompute/plugin.go
  pkg/orchestration/wiring/kubeingress/plugin.go
  pkg/orchestration/wiring/kubeingress/plugin_test.go
  pkg/orchestration/wiring/sqs/plugin.go
  pkg/orchestration/wiring/testdata/e2e.tests.bundle.yaml
  pkg/orchestration/wiring/testdata/ec2compute-rename.bundle.yaml
  pkg/orchestration/wiring/testdata/ec2compute.basicdep.bundle.yaml
  pkg/orchestration/wiring/testdata/k8scompute.basicdep.bundle.yaml
  pkg/orchestration/wiring/testdata/k8scompute.nodefaults.bundle.yaml
  pkg/orchestration/wiring/testdata/k8scompute.nohpa.bundle.yaml
  pkg/orchestration/wiring/testdata/k8scompute.probes.nodefaults.bundle.yaml
  pkg/orchestration/wiring/testdata/k8scompute.rename.bundle.yaml
  pkg/orchestration/wiring/testdata/k8scompute.sameminmax.bundle.yaml
  pkg/orchestration/wiring/wiringplugin/types.go
  pkg/orchestration/wiring/wiringutil/iam/iam.go
  pkg/orchestration/wiring/wiringutil/iam/iam_test.go
  pkg/orchestration/wiring/wiringutil/service_binding.go
  pkg/orchestration/wiring/wiringutil/svccatentangler/plugin.go
Labels: cleanup

#51 Remove version from monitor
  pkg/monitor/objects.go
Labels: cleanup

#67 Scaffolding for status autowiring
  pkg/apis/orchestration/v1/types.go
  pkg/apis/orchestration/v1/zz_generated.deepcopy.go
  pkg/composition/controller_test.go
  pkg/formation/controller_test.go
  pkg/orchestration/BUILD.bazel
  pkg/orchestration/controller.go
  pkg/orchestration/controller_test.go
  pkg/orchestration/wiring/aws/resources.go
  pkg/orchestration/wiring/entangler.go
  pkg/orchestration/wiring/entangler_test.go
  pkg/orchestration/wiring/registry/BUILD.bazel
  pkg/orchestration/wiring/registry/registry.go
  pkg/orchestration/wiring/wiringplugin/BUILD.bazel
  pkg/orchestration/wiring/wiringplugin/types.go
  pkg/orchestration/wiring/wiringplugin/wiring_status_adapter.go
  pkg/util/testutil/object_comparisons.go
Labels: enhancement
